# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 709901822e3db695524efdde000ec80f348c170383a17c69217ff35cd802caac011f87d3a3d4b3d731d9ae37fa401cb451bc7e0018d86ba2cb3cce219ecc1308

test:
  secret_key_base: 601883f51a16c8a880e0c38d871f2245c32140f8bf0b7348dfb9f86e08632e789197208ae131bc5aceceec3a4214ab4c6374fc3c50355265c6ad582f304d3f7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
